# Generated by Django 2.2.28 on 2023-05-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230525_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastAppointment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physicianName',
        ),
    ]
