# Generated by Django 2.2.28 on 2023-05-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230525_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='generalNotes',
        ),
        migrations.AddField(
            model_name='callcenter',
            name='patientId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
