# Generated by Django 2.2.28 on 2023-05-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_user_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='patientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callcenter_patientId', to=settings.AUTH_USER_MODEL),
        ),
    ]
