# Generated by Django 2.2.28 on 2023-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_callcenter_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patientId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
